### PR TITLE
Revert new UI, base image migrated to quay.io

### PR DESCRIPTION
**Pull request by psturc**
### JIRA
https://issues.redhat.com/browse/MGDAPI-2415

### CODE REVIEW

**Comment by matskiv** [comment]
Through the new build pipeline I verified that this builds successfully.

@psturc do you think we need to do some runtime validation? I haven't used UPS in ages :D

**Review by matskiv — APPROVED** [review]

**Comment by psturc** [comment]
@matskiv I can try to replace the UPS image on RHMI cluster with the one I built using the UPS release pipeline and see it still works ok. That could be sufficient, wdyt?

**Comment by psturc** [comment]
I verified that the container image built by the release pipeline runs ok (and also performed crudl operations in UPS UI, all looks good)

Screen Shot 2021-08-16 at 12 40 02

**Comment by psturc** [comment]
@matskiv  I do not have permissions to merge this, feel free to do so

**Comment by matskiv** [comment]
Great news!
Thank you @psturc !

**Pull request merged**
